### ISSUE TITLE
Inward Inventory

### ISSUE THREAD

**Issue by kpooj4** [yashtatsme92/inventory#1]
1. "Invoice number" as label.
2. "Invoice Date" as label.  Input type should be date.
3. Functionality for Add row - this should create a new set of input fields right? Will this be done by you or me?
4. Functionality for Remove row - this should delete the preceding set of input fields right? Will this be done by you or me?
5. Align size of "Remove Row" button as per other input fields.
6. Increase size of "Comments" input field.
7. Try to keep all input fields of same length.

**Comment by yashtatsme92** [comment]
1. "Invoice number" as label. - Done
2. "Invoice Date" as label. Input type should be date. - Done
3. Functionality for Add row - this should create a new set of input fields right? Will this be done by you or me? - Done
4. Functionality for Remove row - this should delete the preceding set of input fields right? Will this be done by you or me? - Done
5. Align size of "Remove Row" button as per other input fields. - Done
6. Increase size of "Comments" input field. - Done
7. Try to keep all input fields of same length. - Done

NOTE: Will take care of the item numbering once you integrate it in your system. Right now it will always append as 1.

**Comment by kpooj4** [comment]
Might have to change the placing of buttons.
Rest its good to go.
