### ISSUE TITLE
Inward Inventory

### ISSUE THREAD

**Issue by kpooj4** [yashtatsme92/inventory#2]
- Add Edit and Update Button

- Product type should be a Radio button with values "Rolled" & "Forged"

-  Weight should be calculated based on formula. There is a separate formula for Square and Round. Selection for Square or 
   Round should be done using Radio button.
   Round formula - (Size*Size*.001881*length)/305
   Square formula - (Size*Size*.0024*length)/305

- All the fields are mandatory except for Heat No and Comments

**Comment by yashtatsme92** [comment]
is this still valid?

**Comment by kpooj4** [comment]
No
