### ISSUE TITLE
Search Page

### ISSUE THREAD

**Issue by kpooj4** [yashtatsme92/inventory#3]
1. Search will be based on 2 filters - Grade and Size
2. Results should include columns 
    a. Series No/No of pieces
    b. Length
    c. Product Type
    d. Manufacturer name
    e. Remark

3. Can you also add the sidebar?
4. Null check for input field
5. Output results will be Datatable.

**Comment by yashtatsme92** [comment]
Search will be based on 2 filters - Grade and Size
- DONE

Results should include columns
a. Series No/No of pieces
b. Length
c. Product Type
d. Manufacturer name
e. Remark
- DONE

Can you also add the sidebar?
- DONE

Null check for input field
- DONE

Output results will be Datatable.
- It is already a DÏata Table

**Comment by yashtatsme92** [comment]
Search will be based on 2 filters - Grade and Size

- DONE

Results should include columns
a. Series No/No of pieces
b. Length
c. Product Type
d. Manufacturer name
e. Remark

- DONE

Can you also add the sidebar?

- DONE

Null check for input field

- DONE

Output results will be Datatable.

- It is already a Data Table
